#!/usr/bin/env bash
killall polybar

PRIMARY=$(xrandr --query | grep " connected" | grep "primary" | cut -d" " -f1)
OTHERS=$(xrandr --query | grep " connected" | grep -v "primary" | cut -d" " -f1)

TRAY=right MONITOR=$PRIAMRY polybar --reload mainbar &
for m in $OTHERS; do
    TRAY=none MONITOR=$m polybar --reload mainbar &
done
